apiVersion: apps/v1
kind: Deployment
metadata:
  name: penpot-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penpot-redis
  template:
    metadata:
      labels:
        app: penpot-redis
    spec:
      containers:
        - name: penpot-redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: penpot-redis
spec:
  selector:
    app: penpot-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
