apiVersion: apps/v1
kind: Deployment
metadata:
  name: huly-cockroachdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huly-cockroachdb
  template:
    metadata:
      labels:
        app: huly-cockroachdb
    spec:
      containers:
        - name: cockroachdb
          image: cockroachdb/cockroach:latest-v24.2
          command: ["cockroach", "start-single-node", "--insecure"]
          env:
            - name: COCKROACH_DATABASE
              value: "huly"
            - name: COCKROACH_USER
              value: "huly"
          ports:
            - containerPort: 26257
            - containerPort: 8080
          volumeMounts:
            - name: cr-data
              mountPath: /cockroach/cockroach-data
      volumes:
        - name: cr-data
          persistentVolumeClaim:
            claimName: huly-cockroachdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cockroach
spec:
  selector:
    app: huly-cockroachdb
  ports:
    - name: sql
      port: 26257
      targetPort: 26257
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huly-cockroachdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
