apiVersion: apps/v1
kind: Deployment
metadata:
  name: huly-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huly-elasticsearch
  template:
    metadata:
      labels:
        app: huly-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.14.2
          command:
            - /bin/sh
            - -c
            - |
              ./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
              /usr/local/bin/docker-entrypoint.sh eswrapper
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms1024m -Xmx1024m"
            - name: http.cors.enabled
              value: "true"
            - name: http.cors.allow-origin
              value: "http://localhost:8082"
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: elastic-data
          persistentVolumeClaim:
            claimName: huly-elasticsearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elastic
spec:
  selector:
    app: huly-elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huly-elasticsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
