apiVersion: apps/v1
kind: Deployment
metadata:
  name: huly-telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huly-telegram-bot
  template:
    metadata:
      labels:
        app: huly-telegram-bot
    spec:
      containers:
        - name: telegram-bot
          image: hardcoreeng/telegram-bot:v0.7.353
          ports:
            - containerPort: 4020
          env:
            - name: PORT
              value: "4020"
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: kq-huly-secrets
                  key: SECRET
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kq-huly-secrets
                  key: TELEGRAM_BOT_TOKEN
            - name: DB_URL
              value: "postgres://huly@cockroach:26257/huly?sslmode=disable"
            - name: ACCOUNTS_URL
              value: "http://huly-account:3000"
            - name: STORAGE_CONFIG
              value: "minio|minio?accessKey=minioadmin&secretKey=minioadmin"
            - name: QUEUE_CONFIG
              value: "redpanda:9092"
            - name: SERVICE_ID
              value: "telegram-bot-service"
            - name: QUEUE_REGION
              value: ""
            - name: DOMAIN
              value: "https://huly.bitspace.org.in/_telegram"
---
apiVersion: v1
kind: Service
metadata:
  name: huly-telegram-bot
spec:
  selector:
    app: huly-telegram-bot
  ports:
    - port: 4020
      targetPort: 4020
